name: endurance-documentation

type: nodejs:18

disk: 512
resources:
    base_memory: 768
    memory_ratio: 768

mounts:
    ".docusaurus": "shared:files/.docusaurus"

web:
    commands:
        start: "npm start"
    locations:
        /img:
            passthru: true

