"https://endurancejs.com/":
  type: upstream
  upstream: "endurance-documentation:http"
"https://www.endurancejs.com/":
  type: redirect
  to: "https://endurancejs.com/"
"http://{default}/":
  type: redirect
  to: "https://{default}/"
